export const users = [
  { id: 1, name: "강예훈", age: 25, email: "yehoon@example.com" },
  { id: 2, name: "홍길동", age: 30, email: "gil@example.com" },
  { id: 3, name: "김영희", age: 28, email: "younghee@example.com" },
  { id: 4, name: "이민호", age: 35, email: "minho@example.com" },
  { id: 5, name: "박지은", age: 24, email: "jieun@example.com" },
  { id: 6, name: "최승훈", age: 27, email: "seunghoon@example.com" },
  { id: 7, name: "조민수", age: 32, email: "minsuh@example.com" },
  { id: 8, name: "장동건", age: 40, email: "donggun@example.com" },
  { id: 9, name: "한지민", age: 29, email: "jimin@example.com" },
  { id: 10, name: "임수정", age: 26, email: "soojung@example.com" },
  { id: 11, name: "고경표", age: 31, email: "kyungpyo@example.com" },
  { id: 12, name: "송중기", age: 36, email: "joongki@example.com" },
  { id: 13, name: "차태현", age: 34, email: "taehyun@example.com" },
  { id: 14, name: "류준열", age: 33, email: "junyeol@example.com" },
  { id: 15, name: "김수현", age: 32, email: "soohyun@example.com" },
  { id: 16, name: "전지현", age: 38, email: "jihyun@example.com" },
  { id: 17, name: "이준기", age: 39, email: "joongi@example.com" },
  { id: 18, name: "박서준", age: 29, email: "seojun@example.com" },
  { id: 19, name: "김태리", age: 26, email: "taeri@example.com" },
  { id: 20, name: "김민재", age: 28, email: "minjae@example.com" },
];
